spring:
  config:
    activate:
      on-profile: integration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://eum-db:3306/eum_schema?autoreconnect=true
    username: user
    password: 1234
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  flyway:
    url: jdbc:mysql://eum-db:3306?autoreconnect=true
    schemas: eum_schema
    user: "user"
    password: "1234"
    locations: classpath:/db/migration,classpath:/db/testdata-integration
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        current_session_context_class=org: springframework.orm.hibernate5.SpringSessionContext
    show-sql: true

springdoc:
  api-docs:
    path: /eum-docs
  swagger-ui:
    path: /eum-ui.html

application:
  title: "EUM"
  description: "Electronic University Management"
  version: "1.0.0"
